<template>
  <div class="stake-seen">
    <container>
      <fenced-title
        class="flex-grow mr-0 mb-2 self-stretch"
        color="fence-gray"
        textAlign="center"
        :closed="true"
        >Stake Seen</fenced-title
      >
      <div
        class="description text-gray-600 mx-auto text-center py-4 text-lg max-w-lg mb-6"
      >
        Deposit your SEEN in the pool and start earning fees generated by the
        SEEN Protocol.
      </div>

      <div
        class="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 bg-background-gray p-9 rounded-lg border mb-20"
      >
        <div class="flex flex-col items-center xl:items-start mb-6 xl:mb-0">
          <div class="text-sm text-gray-400 font-semibold uppercase mb-1">
            TLV (USD) <i class="fas fa-info-circle"></i>
          </div>
          <div class="text-3xl font-black">$7,184,371.38</div>
        </div>

        <div class="flex flex-col items-center xl:items-start mb-6 xl:mb-0">
          <div class="text-sm text-gray-400 font-semibold uppercase mb-1">
            TOTAL SEEN LOCKED <i class="fas fa-info-circle"></i>
          </div>
          <div class="text-3xl font-black flex">
            <i class="fas fa-circle text-lg text-gray-300 mr-2"></i>
            23,091,369
          </div>
        </div>

        <div class="flex flex-col items-center xl:items-start mb-6 md:mb-0">
          <div class="text-sm text-gray-400 font-semibold uppercase mb-1">
            Your stake <i class="fas fa-info-circle"></i>
          </div>
          <div class="text-3xl font-black flex">
            <i class="fas fa-circle text-lg text-gray-300 mr-2"></i>623.6
          </div>
        </div>

        <div class="flex flex-col items-center xl:items-start">
          <div class="text-sm text-gray-400 font-semibold uppercase mb-1">
            Your share of the pool <i class="fas fa-info-circle"></i>
          </div>
          <div class="text-3xl font-black">1,55%</div>
        </div>
      </div>

      <div class="cards flex flex-col xl:flex-row">
        <stake-or-withdraw-card class="mr-0 mb-12 xl:mb-0 xl:mr-12" />
        <stake-or-withdraw-card type="withdraw" />
      </div>
    </container>

    <div class="bg-background-gray border-t pb-28 pt-52 -mt-32">
      <container class="py-6">
        <fenced-title
          class="flex-grow mr-0 mb-2 self-stretch"
          color="fence-gray"
          textAlign="center"
          :closed="true"
          >How to Stake
          <span class="text-primary italic">Seen?</span></fenced-title
        >

        <div class="list max-w-xl mx-auto mt-12">
          <div
            class="flex bg-white border rounded-lg p-4 items-center font-bold mb-2"
          >
            <span
              class="rounded-full bg-black text-white flex items-center justify-center w-8 h-8 mr-4"
              >1</span
            >
            Deposit your SEEN
          </div>
          <div
            class="flex bg-white border rounded-lg p-4 items-center font-bold mb-2"
          >
            <span
              class="rounded-full bg-black text-white flex items-center justify-center w-8 h-8 mr-4"
              >2</span
            >
            You start earning ETH and WBTC right away.
          </div>
          <div
            class="flex bg-white border rounded-lg p-4 items-center font-bold mb-2"
          >
            <span
              class="rounded-full bg-black text-white flex items-center justify-center w-8 h-8 mr-4"
              >3</span
            >
            Yes, both ETH and WBTC.
          </div>
          <div
            class="flex bg-white border rounded-lg p-4 items-center font-bold mb-2"
          >
            <span
              class="rounded-full bg-black text-white flex items-center justify-center w-8 h-8 mr-4"
              >4</span
            >
            You can withdraw your HEGIC anytime*.
          </div>

          <div class="text-2xs text-gray-400 px-4 mt-3">
            * If enough liquidity available. 24h period may apply due to HEGIC
            limitations.
          </div>
        </div>
      </container>
    </div>
  </div>
</template>

<script>
import { useMeta } from "vue-meta";

import FencedTitle from "@/components/FencedTitle.vue";
import Container from "@/components/Container.vue";
import StakeOrWithdrawCard from "@/views/stake/components/StakeOrWithdrawCard";

export default {
  name: "Stake",
  components: { FencedTitle, Container, StakeOrWithdrawCard },
  setup() {
    const { meta } = useMeta({
      title: "Stake",
    });
  }
};
</script>

<style scoped>
</style>
